baseURL = "https://kamatvedita99.netlify.app"
disableLanguages = []
disqusShortname = "themefisher-template"
googleAnalytics = ""
hasCJKLanguage = true
paginate = "4"
summaryLength = "15"
theme = "iWriter-hugo"
timeZone = "UTC"
title = "Vedita Kamat"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.88.1"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
