[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "Contact"
url = "contact/"
weight = 3
[[main]]
hasChildren = true
name = "Pages"
weight = 5
[[main]]
name = "Blog Details"
parent = "Pages"
url = "blog/post-1/"
[[main]]
name = "Category"
parent = "Pages"
url = "categories/travel"
